In [1]:
# We are going to create a MLP that classifies triangles.
# 1. Create data (triples) of side lengths, and also angles.  (Consider differences in data.)
# 2. Label these data with a labeling function.  (Notice differences in labels.)
# 3. Create a MLP model for each.  (What do you expect from learning/performance?)
# 4. Pass respective data and labels into MLP model, and run fit loop.  
# 5. Plot and visualize results.  (Discuss)

In [2]:
# We could create a model which learns to "finish" triangles from two thirds of a triple.
# However, we already know the pythagorean theorem, which we will use for labeling.
# This is a toy model for illustration purposes.

In [3]:
from sklearn.neural_network import MLPClassifier
import numpy as np

In [4]:
# Create data (two different paths).  Stick with integers for simplicity.

In [5]:
def create_data_sides(num_side_triples):
    # Does it matter the range we choose for side lengths?
    side_triples = np.random.randint(low=1, high=1000, size=(num_side_triples, 3))
    return side_triples

In [6]:
def create_data_angles(num_angle_triples):
    # Some reasonable bounds on (integer) angles are [1,179).  Why?  
    # Could we choose other bounds for creating the distribution of integer degrees?
    angle_triples = np.random.randint(low=1, high=179, size=(num_angle_triples, 3))
    return angle_triples

In [7]:
# How much data do we want to generate.
num_data = 4

In [8]:
create_data_sides(num_data)

array([[903, 504, 279],
       [563, 261, 524],
       [768, 588, 487],
       [453,   6, 878]])

In [9]:
create_data_angles(num_data)

array([[145, 102,  32],
       [ 79,  76,   4],
       [  7, 163, 112],
       [167, 172,  13]])

In [10]:
def side_labeler(side_data):
    '''
    Function takes ONLY side data and returns labels of successful triangles.
    '''
    # Labels are a vector of length of side_data, equal to 1 where Triangle Inequality Theorem holds.
    # https://en.wikipedia.org/wiki/Triangle_inequality
    
    # Grab longest side for each potential triangle, and compare with sum of other lengths.
    # One way to achieve this is to first sort the sides so that the longest side is last.
    side_data = np.array([sorted(i) for i in side_data])

    # Then compare and create labels (using list comprehension) according to the Theorem.
    labels = np.array([1 if (i[-1] <= i[0] + i[1]) else 0 for i in side_data])
    
    return labels

In [11]:
def angle_labeler(angle_data):
    '''
    Function takes ONLY angle data and returns labels of successful triangles.
    '''
    # Labeling angles is a bit more simple.  Simply check they sum to 180 degrees.
    labels = np.array([1 if (i[0] + i[1] + i[2] == 180) else 0 for i in angle_data])
    return labels

In [12]:
# Test side data creation
sides = create_data_sides(100)
sides

array([[705,  76, 731],
       [997,  39, 686],
       [167, 650, 525],
       [560, 403, 669],
       [395, 683, 771],
       [435, 386, 313],
       [939, 451, 235],
       [904, 913, 753],
       [ 90, 459, 125],
       [602, 328, 349],
       [ 48, 535, 186],
       [949, 405, 484],
       [ 81, 670, 949],
       [616, 513, 773],
       [504, 658,  98],
       [777, 659, 858],
       [152, 923, 855],
       [456, 815, 602],
       [879, 839, 898],
       [937, 433, 203],
       [122, 779, 107],
       [234, 995, 331],
       [967, 933, 378],
       [650, 695, 212],
       [ 17, 515, 387],
       [501, 488, 239],
       [228, 755, 117],
       [522, 546, 565],
       [687, 193, 561],
       [926, 279, 645],
       [176, 947, 186],
       [560, 551, 806],
       [511, 526, 913],
       [ 72, 927, 534],
       [779, 553, 674],
       [592, 671, 246],
       [487, 592, 130],
       [938,  76, 171],
       [ 44, 928, 408],
       [455, 783, 625],
       [ 67, 608, 731],
       [905, 468

In [13]:
# Test side labeling.  Sanity check by hand.
side_labels = side_labeler(sides)
side_labels

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [20]:
# Test angle data creation
angles = create_data_angles(100)
angles

array([[ 29,   9, 175],
       [ 67, 118, 141],
       [178, 157,  70],
       [ 75, 110,  63],
       [ 63,  99,  64],
       [148, 177,  22],
       [174,  37,  20],
       [  8,  43, 167],
       [101,  44, 137],
       [172, 110,  58],
       [ 44, 176,  80],
       [134,  68,  90],
       [ 76, 136, 118],
       [ 27,  39, 149],
       [153,  27,  95],
       [ 31, 111,  21],
       [115, 149, 148],
       [156,  89,   9],
       [178,  22,  29],
       [ 85, 128,  21],
       [ 29,  44, 121],
       [ 88, 122, 122],
       [ 68, 158, 117],
       [103,  40,  69],
       [ 12,  77,  69],
       [ 71,   9,  21],
       [124,  97, 117],
       [160,  30,  77],
       [ 65,   9,  51],
       [170,  32,  88],
       [130,  97, 165],
       [ 47,  33,  44],
       [147, 134, 145],
       [119, 136,  48],
       [ 37, 124,  14],
       [ 78, 164,  70],
       [ 97,  40,  18],
       [  3,  78,   5],
       [ 27, 121,  19],
       [150,  88, 163],
       [ 10, 137, 134],
       [ 76, 165

In [21]:
# Test angle labeling. Sanity check.
angle_labels = angle_labeler(angles)
angle_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# What is one main difference between angle labels and side labels?

In [17]:
side_classifier = MLPClassifier(max_iter=100).fit(sides,side_labels)

In [18]:
predicted_sides = side_classifier.predict(sides)
predicted_sides

array([0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [19]:
predicted_sides == side_labels

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [22]:
# Note: We should test on a separate data set, normal practice is to split the training data.

In [23]:
# For angle classification, consider the information we are feeding into the MLP.
angle_classifier = MLPClassifier(max_iter=100).fit(angles,angle_labels)

In [24]:
predicted_angles = angle_classifier.predict(angles)
predicted_angles

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Wow, incredible performance!  ...Or is something wrong?
predicted_angles == angle_labels

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])