In [1]:
# We are going to create a MLP that classifies triangles.
# 1. Create data (triples) of side lengths, and also angles.  (Consider differences in data.)
# 2. Label these data with a labeling function.  (Notice differences in labels.)
# 3. Create a MLP model for each.  (What do you expect from learning/performance?)
# 4. Pass respective data and labels into MLP model, and run fit loop.  
# 5. Plot and visualize results.  (Discuss)

In [2]:
# This is a toy model for illustration purposes.

In [3]:
from sklearn.neural_network import MLPClassifier
import numpy as np

In [4]:
# Create data (two different paths).  Stick with integers for simplicity.

In [5]:
def create_data_sides(num_side_triples):
    '''
    Function creates triangle side data.
    '''
    # Does it matter the range we choose for side lengths?
    side_triples = np.random.randint(low=1, high=1000, size=(num_side_triples, 3))
    return side_triples

In [6]:
def create_data_angles(num_angle_triples):
    '''
    Function creates triangle angle data.
    '''
    # Some reasonable bounds on (integer) angles are [1,179).  Why?  
    # Could we choose other bounds for creating the distribution of integer degrees?
    angle_triples = np.random.randint(low=1, high=179, size=(num_angle_triples, 3))
    return angle_triples

In [7]:
# How much data do we want to generate.
num_data = 4

In [8]:
create_data_sides(num_data)

array([[636,  28, 858],
       [811, 507, 550],
       [595, 208, 212],
       [598, 862, 686]])

In [9]:
create_data_angles(num_data)

array([[ 42, 117, 163],
       [  6, 163, 100],
       [ 50, 152,  43],
       [ 42, 143,  50]])

In [10]:
def side_labeler(side_data):
    '''
    Function takes ONLY side data and returns labels of successful triangles.
    '''
    # Labels are a vector of length of side_data, equal to 1 where Triangle Inequality Theorem holds.
    # https://en.wikipedia.org/wiki/Triangle_inequality
    
    # Grab longest side for each potential triangle, and compare with sum of other lengths.
    # One way to achieve this is to first sort the sides so that the longest side is last.
    side_data = np.array([sorted(i) for i in side_data])

    # Then compare and create labels (using list comprehension) according to the Theorem.
    labels = np.array([1 if (i[-1] <= i[0] + i[1]) else 0 for i in side_data])
    
    return labels

In [11]:
def angle_labeler(angle_data):
    '''
    Function takes ONLY angle data and returns labels of successful triangles.
    '''
    # Labeling angles is a bit more simple.  Simply check they sum to 180 degrees.
    labels = np.array([1 if (i[0] + i[1] + i[2] == 180) else 0 for i in angle_data])
    return labels

In [12]:
# Test side data creation
sides = create_data_sides(100)
sides

array([[408, 252,  73],
       [406, 352, 447],
       [982,  40, 510],
       [260, 943, 268],
       [709, 816, 334],
       [162, 201, 878],
       [350, 489, 457],
       [807, 534, 969],
       [363, 275, 220],
       [581, 140, 493],
       [756, 200, 938],
       [ 26, 352, 915],
       [921,  74, 417],
       [937, 734, 961],
       [466, 598, 962],
       [239, 461, 968],
       [527,  59, 434],
       [760, 598, 186],
       [420, 470, 902],
       [978, 394, 788],
       [802,   5, 329],
       [167, 761, 559],
       [461, 967, 463],
       [631,   1, 882],
       [186, 605, 465],
       [886, 966, 333],
       [567,  23, 538],
       [651,  53, 501],
       [840, 983, 499],
       [378, 627, 837],
       [987,  20, 773],
       [492,  19, 835],
       [117, 844, 765],
       [472, 753, 978],
       [146, 853,  14],
       [786, 429, 129],
       [232, 667, 837],
       [691, 275, 795],
       [369, 346, 612],
       [393, 730, 355],
       [  9, 486, 670],
       [ 94, 990

In [13]:
# Test side labeling.  Sanity check by hand.
side_labels = side_labeler(sides)
side_labels

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [14]:
# Test angle data creation
angles = create_data_angles(100)
angles

array([[ 71, 176, 136],
       [ 48, 128, 169],
       [  7,  35,  71],
       [ 31,  82, 123],
       [ 87, 123, 178],
       [ 83,  53, 143],
       [108,  82,  84],
       [ 59, 158, 114],
       [162,  69,   9],
       [137,  21, 114],
       [ 69, 168,  85],
       [ 21,  83, 168],
       [113, 101,  50],
       [ 55,  33, 144],
       [ 89,  24,  31],
       [145,  49,  90],
       [ 99,  43, 152],
       [159,  13,  39],
       [106,  30,  40],
       [173,  38, 129],
       [147,  33, 104],
       [ 57,  20, 151],
       [ 92, 119,  30],
       [ 24, 116,   1],
       [ 69,  19, 115],
       [ 67,  43,  76],
       [147,   5, 117],
       [ 64,  62, 113],
       [166,  39, 165],
       [ 78, 105, 120],
       [138,   2,  39],
       [ 57,  54,  34],
       [163, 162, 136],
       [143, 158,  15],
       [150,  98, 101],
       [ 70,  64, 106],
       [ 97,  17, 172],
       [ 92,   9,  25],
       [ 53,  32,  23],
       [ 57,  98, 140],
       [163, 153,  87],
       [ 13,  23

In [15]:
# Test angle labeling. Sanity check.
angle_labels = angle_labeler(angles)
angle_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# What is one main difference between angle labels and side labels?

In [17]:
side_classifier = MLPClassifier(max_iter=100).fit(sides,side_labels)

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [18]:
predicted_sides = side_classifier.predict(sides)
predicted_sides

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [19]:
predicted_sides == side_labels

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
# Note: We should test on a separate data set, normal practice is to split the training data.

In [21]:
# For angle classification, consider the information we are feeding into the MLP.
angle_classifier = MLPClassifier(max_iter=100).fit(angles,angle_labels)

In [22]:
predicted_angles = angle_classifier.predict(angles)
predicted_angles

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Wow, incredible performance!  ...Or is something wrong?
predicted_angles == angle_labels

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])