In [1]:
# We are going to create a MLP that classifies triangles.
# 1. Create data (triples) of side lengths, and also angles.  (Consider how to structure data.)
# 2. Label these data with a labeling function.
# 3. Create a MLP model.
# 4. Pass data and labels into MLP model, and run fit loop.  (Which data?)
# 5. 

In [2]:
# We could create a model which learns to "finish" triangles from two thirds of a triple.
# However, we already know the pythagorean theorem, which we will use for labeling.
# This is a toy model for illustration purposes.

In [3]:
from sklearn.neural_network import MLPClassifier
import numpy as np

In [4]:
# Create data (two different paths).  Stick with integers for simplicity.

In [5]:
def create_data_sides(num_side_triples):
    # Does it matter the range we choose for side lengths?
    side_triples = np.random.randint(low=1, high=1000, size=(num_side_triples, 3))
    return side_triples

In [6]:
def create_data_angles(num_angle_triples):
    # Some reasonable bounds on (integer) angles are [1,179).  Why?  
    # Could we choose other bounds for creating the distribution of integers?
    angle_triples = np.random.randint(low=1, high=179, size=(num_angle_triples, 3))
    return angle_triples

In [7]:
# How much data do we want to generate.
num_data = 4

In [8]:
create_data_sides(num_data)

array([[574, 629, 952],
       [258, 449, 410],
       [998,  33, 937],
       [338, 786, 562]])

In [9]:
create_data_angles(num_data)

array([[  5, 142, 119],
       [ 32,  54,  94],
       [171, 131, 109],
       [129,  82, 116]])

In [13]:
def side_labeler(side_data):
    # Labels are a vector of length of side_data, equal to 1 where Triangle Inequality Theorem holds.
    # https://en.wikipedia.org/wiki/Triangle_inequality
    
    # Grab longest side for each potential triangle, and compare with sum of other lengths.
    # One way to achieve this is to first sort the sides so that the longest side is last.
    side_data = np.array([sorted(i) for i in side_data])

    # Then compare and create labels (using list comprehension) according to the Theorem.
    labels = np.array([1 if (i[-1] <= i[0] + i[1]) else 0 for i in side_data])
    
    return labels

In [ ]:
def angle_labeler(angle_data):
    pass

In [12]:
# Test side data creation
sides = create_data_sides(20)
sides

array([[ 95, 791, 232],
       [590, 361, 717],
       [ 74,  91, 533],
       [278, 911, 875],
       [292, 728, 898],
       [191,  65, 599],
       [325, 436, 115],
       [ 18, 366, 990],
       [613, 260, 136],
       [317, 549, 666],
       [272, 401, 355],
       [ 74, 723, 759],
       [660, 588,  87],
       [175,  28, 518],
       [ 25, 880, 836],
       [894, 653,  10],
       [866, 787, 351],
       [505, 190, 702],
       [910, 857, 323],
       [301, 809, 437]])

In [15]:
# Test side labeling.  Sanity check by hand.
side_labels = side_labeler(sides)
side_labels

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0])